# Generated by Django 3.0.7 on 2020-10-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_file_studentcourse_teachercourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='courses',
            name='department_name',
        ),
        migrations.AddField(
            model_name='file',
            name='course_id',
            field=models.ManyToManyField(to='main.courses'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='department_id',
            field=models.ManyToManyField(to='main.department'),
        ),
        migrations.AddField(
            model_name='student',
            name='department_id',
            field=models.ManyToManyField(to='main.department'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='department_id',
            field=models.ManyToManyField(to='main.department'),
        ),
    ]
