# Generated by Django 3.0.7 on 2020-10-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201002_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='courses',
            name='department_id',
        ),
        migrations.AddField(
            model_name='courses',
            name='department_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='file',
            name='course_id',
        ),
        migrations.AddField(
            model_name='file',
            name='course_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.RemoveField(
            model_name='studentcourse',
            name='course_id',
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='course_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.RemoveField(
            model_name='studentcourse',
            name='student_id',
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='student_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.RemoveField(
            model_name='teachercourse',
            name='course_id',
        ),
        migrations.AddField(
            model_name='teachercourse',
            name='course_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.RemoveField(
            model_name='teachercourse',
            name='teacher_id',
        ),
        migrations.AddField(
            model_name='teachercourse',
            name='teacher_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
