# Generated by Django 3.0.7 on 2020-10-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201002_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='descreption',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
